version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: frontend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: backend