apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: silteo/backend:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8081