FROM node AS build
COPY frontend frontend/
WORKDIR frontend
RUN npm run build
FROM nginx:stable
COPY - from=build /frontend/dist/ /var/www
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx -g 'daemon off;'"]