version: '3'

services:

    postgres:
      image: postgres:9.6
      ports:
          - 5432:5432
      environment:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo

    backend:
       image: backend:latest
       ports:
         - 8081:8081

    frontend:
       image: frontend:latest
       ports:
         - 8080:8080