FROM openjdk:8-jdk-alpine
VOLUME /tmp

#WORKDIR backend

COPY backend/ /backend/

RUN cd backend; ./gradlew assemble

#ARG JAR_FILE
#COPY ${JAR_FILE} backend.jar

#RUN cp backend/build/libs/demo-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./backend/build/libs/demo-0.0.1-SNAPSHOT.jar"]